{
  "openapi": "3.1.0",
  "info": {
    "title": "Tracks API v1",
    "description": "",
    "version": "1.0.0"
  },
  "tags": [
    {
      "name": "tracks"
    },
    {
      "name": "artists"
    },
    {
      "name": "albums"
    }
  ],
  "paths": {
    "/tracks": {
      "get": {
        "summary": "Filter tracks",
        "deprecated": false,
        "description": "Get a list of tracks using optional filters.",
        "tags": [
          "tracks"
        ],
        "parameters": [
          {
            "name": "limit",
            "in": "query",
            "description": "Specifies the maximum number of items to return.",
            "required": false,
            "schema": {
              "type": "integer",
              "description": "Specifies the maximum number of items to return.",
              "default": 20,
              "maximum": 100,
              "minimum": 1
            }
          },
          {
            "name": "offset",
            "in": "query",
            "description": "Specifies the starting index of the data.",
            "required": false,
            "schema": {
              "type": "integer",
              "description": "Specifies the starting index of the data.",
              "minimum": 0,
              "default": 0
            }
          },
          {
            "name": "sort",
            "in": "query",
            "description": "Specifies the column to sort by.",
            "required": false,
            "schema": {
              "type": "string",
              "description": "Specifies the column to sort by.",
              "enum": [
                "created_at",
                "updated_at",
                "id"
              ],
              "default": "id"
            }
          },
          {
            "name": "name",
            "in": "query",
            "description": "The name of the track.",
            "required": false,
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "artist",
            "in": "query",
            "description": "The name of the artist.",
            "required": false,
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "album",
            "in": "query",
            "description": "The name of the album.",
            "required": false,
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "genre",
            "in": "query",
            "description": "The genre.",
            "required": false,
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "year",
            "in": "query",
            "description": "The year the track was released.",
            "required": false,
            "schema": {
              "type": "integer"
            }
          },
          {
            "name": "mode",
            "in": "query",
            "description": "Major or minor.",
            "required": false,
            "schema": {
              "type": [
                "integer",
                "null"
              ],
              "description": "Major or minor.",
              "enum": [
                0,
                1
              ]
            }
          },
          {
            "name": "min_total_playcount",
            "in": "query",
            "description": "Specifies the minimum value for total play count.",
            "required": false,
            "schema": {
              "type": "integer"
            }
          },
          {
            "name": "max_total_playcount",
            "in": "query",
            "description": "Specifies the maximum value for total play count.",
            "required": false,
            "schema": {
              "type": "integer"
            }
          },
          {
            "name": "tags",
            "in": "query",
            "description": "Tags describing the genres the track belongs to.",
            "required": false,
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "artist_id",
            "in": "query",
            "description": "Specifies the artist ID.",
            "required": false,
            "schema": {
              "type": "integer"
            }
          },
          {
            "name": "album_id",
            "in": "query",
            "description": "Specifies the album ID.",
            "required": false,
            "schema": {
              "type": "integer"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Successful operation.",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "status": {
                      "type": "integer",
                      "description": "HTTP status code",
                      "minimum": 100,
                      "maximum": 999,
                      "default": 200
                    },
                    "href": {
                      "type": "string",
                      "title": "",
                      "description": "self-link"
                    },
                    "next": {
                      "type": [
                        "string",
                        "null"
                      ],
                      "description": "URL to next page"
                    },
                    "previous": {
                      "type": [
                        "string",
                        "null"
                      ],
                      "description": "URL to previous page"
                    },
                    "data": {
                      "type": "array",
                      "items": {
                        "$ref": "#/components/schemas/Track"
                      }
                    }
                  },
                  "required": [
                    "data",
                    "status",
                    "href",
                    "next",
                    "previous"
                  ]
                },
                "example": {
                  "status": 200,
                  "href": "http://patriciaj.se/tracks-api/api/v1/tracks?limit=2&offset=0&sort=id&artist_id=12",
                  "next": "http://patriciaj.se/tracks-api/api/v1/tracks?limit=2&offset=2&sort=id&artist_id=12",
                  "previous": null,
                  "data": [
                    {
                      "id": 18,
                      "href": "http://patriciaj.se/tracks-api/api/v1/tracks/18",
                      "created_at": "2026-06-16T13:45:35.877848Z",
                      "updated_at": "2026-06-16T13:45:35.877848Z",
                      "name": "In the End",
                      "total_playcount": 80,
                      "spotify_id": "138JuTi1U3WIROalXod9FB",
                      "tags": "\"rock, alternative, metal, alternative_rock, nu_metal\"",
                      "genre": "NaN",
                      "year": 2000,
                      "duration_ms": 216933,
                      "danceability": 0.542,
                      "mode": 0,
                      "valence": 0.37,
                      "artists": [
                        {
                          "id": 12,
                          "href": "http://patriciaj.se/tracks-api/api/v1/artists/12"
                        }
                      ],
                      "albums": [
                        {
                          "id": 17,
                          "href": "http://patriciaj.se/tracks-api/api/v1/albums/17"
                        }
                      ]
                    },
                    {
                      "id": 30,
                      "href": "http://patriciaj.se/tracks-api/api/v1/tracks/30",
                      "created_at": "2026-06-16T13:45:35.877848Z",
                      "updated_at": "2026-06-16T13:45:35.877848Z",
                      "name": "Numb",
                      "total_playcount": 19,
                      "spotify_id": "0kO3njY9N1Rxgv27Ha1lLh",
                      "tags": "\"rock, alternative, metal, alternative_rock, nu_metal\"",
                      "genre": "NaN",
                      "year": 2003,
                      "duration_ms": 185586,
                      "danceability": 0.496,
                      "mode": 1,
                      "valence": 0.243,
                      "artists": [
                        {
                          "id": 12,
                          "href": "http://patriciaj.se/tracks-api/api/v1/artists/12"
                        }
                      ],
                      "albums": [
                        {
                          "id": 29,
                          "href": "http://patriciaj.se/tracks-api/api/v1/albums/29"
                        }
                      ]
                    }
                  ]
                }
              }
            },
            "headers": {}
          },
          "400": {
            "$ref": "#/components/responses/Bad Request",
            "description": "The request cannot or will not be processed due to something that is perceived to be a client error (for example validation error)."
          },
          "500": {
            "$ref": "#/components/responses/Internal Server Error",
            "description": "The server encountered an unexpected condition that prevented it from fulfilling the request."
          }
        },
        "security": []
      },
      "post": {
        "summary": "Create a track",
        "deprecated": false,
        "description": "Add a track to the collection. Requires authentication.",
        "tags": [
          "tracks"
        ],
        "parameters": [],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/TrackPayload"
              },
              "examples": {
                "1": {
                  "value": {
                    "name": "Don't Stay",
                    "year": 2003,
                    "artist_ids": [
                      12
                    ],
                    "album_ids": [
                      29
                    ],
                    "total_playcount": 153000,
                    "spotify_id": "v0aZ3KQxOQR63T5Zt506M",
                    "tags": [
                      "metal",
                      "nu_metal",
                      "rock"
                    ],
                    "genre": "nu_metal",
                    "duration_ms": 188000,
                    "danceability": 0.453,
                    "mode": 0,
                    "valence": 0.243
                  },
                  "summary": "Example"
                },
                "2": {
                  "value": {
                    "name": "Don't Stay",
                    "year": 2003,
                    "artist_ids": [
                      12
                    ],
                    "album_ids": [
                      29
                    ]
                  },
                  "summary": "Example with only required fields"
                }
              }
            }
          },
          "required": true
        },
        "responses": {
          "201": {
            "description": "Successful operation.",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "status": {
                      "type": "integer",
                      "description": "HTTP status code",
                      "minimum": 0,
                      "maximum": 999,
                      "default": 201
                    },
                    "data": {
                      "$ref": "#/components/schemas/Track",
                      "description": "The created track."
                    }
                  },
                  "required": [
                    "status",
                    "data"
                  ]
                },
                "examples": {
                  "1": {
                    "summary": "Example",
                    "value": {
                      "status": 201,
                      "data": {
                        "id": 25002,
                        "href": "https://patriciaj.se/tracks-api/api/v1/tracks/25002",
                        "created_at": "2026-06-15T10:42:23.946788+00:00",
                        "updated_at": "2026-06-15T10:42:23.946788+00:00",
                        "name": "Don't Stay",
                        "total_playcount": 153000,
                        "spotify_id": "v0aZ3KQxOQR63T5Zt506M",
                        "tags": "[metal,nu_metal rock]",
                        "genre": "nu_metal",
                        "year": 2003,
                        "duration_ms": 188000,
                        "danceability": 0.453,
                        "mode": 0,
                        "valence": 0.243,
                        "artists": [
                          {
                            "id": 12,
                            "href": "https://patriciaj.se/tracks-api/api/v1/artists/12"
                          }
                        ],
                        "albums": [
                          {
                            "id": 29,
                            "href": "https://patriciaj.se/tracks-api/api/v1/albums/29"
                          }
                        ]
                      }
                    }
                  },
                  "2": {
                    "summary": "Example when only sending required fields",
                    "value": {
                      "status": 200,
                      "data": {
                        "id": 25002,
                        "href": "https://patriciaj.se/tracks-api/api/v1/tracks/25002",
                        "created_at": "2026-06-15T10:42:23.946788+00:00",
                        "updated_at": "2026-06-15T10:42:23.946788+00:00",
                        "name": "Don't Stay",
                        "total_playcount": 0,
                        "spotify_id": null,
                        "tags": null,
                        "genre": null,
                        "year": 2003,
                        "duration_ms": null,
                        "danceability": null,
                        "mode": null,
                        "valence": null,
                        "artists": [
                          {
                            "id": 12,
                            "href": "https://patriciaj.se/tracks-api/api/v1/artists/12"
                          }
                        ],
                        "albums": [
                          {
                            "id": 29,
                            "href": "https://patriciaj.se/tracks-api/api/v1/albums/29"
                          }
                        ]
                      }
                    }
                  }
                }
              }
            },
            "headers": {}
          },
          "400": {
            "$ref": "#/components/responses/Bad Request",
            "description": "The request cannot or will not be processed due to something that is perceived to be a client error (for example validation error)."
          },
          "401": {
            "$ref": "#/components/responses/Unauthorized",
            "description": "Credentials invalid or not provided."
          },
          "500": {
            "$ref": "#/components/responses/Internal Server Error",
            "description": "The server encountered an unexpected condition that prevented it from fulfilling the request."
          }
        },
        "security": [
          {
            "bearer": []
          }
        ]
      }
    },
    "/tracks/{id}": {
      "get": {
        "summary": "Get a track by ID",
        "deprecated": false,
        "description": "Get a track by ID.",
        "tags": [
          "tracks"
        ],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "description": "The track ID.",
            "required": true,
            "schema": {
              "type": "integer",
              "description": "The ID of the resource.",
              "minimum": 1
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Successful operation.",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "status": {
                      "type": "integer",
                      "description": "HTTP status code"
                    },
                    "data": {
                      "$ref": "#/components/schemas/Track"
                    }
                  },
                  "required": [
                    "status",
                    "data"
                  ]
                },
                "example": {
                  "status": 200,
                  "data": {
                    "id": 4,
                    "href": "https://patriciaj.se/tracks-api/api/v1/tracks/4",
                    "created_at": "2026-06-15T09:30:19.017659Z",
                    "updated_at": "2026-06-15T09:30:19.017659Z",
                    "name": "Take Me Out",
                    "total_playcount": 21,
                    "spotify_id": "0ancVQ9wEcHVd0RrGICTE4",
                    "tags": "\"rock, alternative, indie, alternative_rock, indie_rock, british, 00s, britpop\"",
                    "genre": "NaN",
                    "year": 2004,
                    "duration_ms": 237026,
                    "danceability": 0.279,
                    "mode": 1,
                    "valence": 0.49,
                    "artists": [
                      {
                        "id": 4,
                        "href": "https://patriciaj.se/tracks-api/api/v1/artists/4"
                      }
                    ],
                    "albums": [
                      {
                        "id": 4,
                        "href": "https://patriciaj.se/tracks-api/api/v1/albums/4"
                      }
                    ]
                  }
                }
              }
            },
            "headers": {}
          },
          "404": {
            "$ref": "#/components/responses/Not Found",
            "description": "The requested resource was not found."
          },
          "500": {
            "$ref": "#/components/responses/Internal Server Error",
            "description": "The server encountered an unexpected condition that prevented it from fulfilling the request."
          }
        },
        "security": []
      },
      "put": {
        "summary": "Update a track",
        "deprecated": false,
        "description": "Edit a track.",
        "tags": [
          "tracks"
        ],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "description": "The ID of the resource.",
            "required": true,
            "schema": {
              "type": "integer",
              "description": "The ID of the resource",
              "minimum": 1
            }
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/TrackPayload"
              },
              "example": {
                "name": "Irreplaceable",
                "year": 2026,
                "artist_ids": [
                  250,
                  3998
                ],
                "album_ids": [
                  4484
                ],
                "total_playcount": 6572114805222890,
                "spotify_id": "ZGqLzifOYwG33nVgRHw0F",
                "tags": [
                  "Alternative",
                  "Southern Gospel",
                  "Progressive House"
                ],
                "genre": "Alternative",
                "duration_ms": 151043,
                "danceability": 0.583,
                "mode": 1,
                "valence": 0.413
              }
            }
          },
          "required": true
        },
        "responses": {
          "204": {
            "description": "The server successfully processed the request and is not returning any content.",
            "headers": {}
          },
          "400": {
            "$ref": "#/components/responses/Bad Request",
            "description": "The request cannot or will not be processed due to something that is perceived to be a client error (for example validation error)."
          },
          "401": {
            "$ref": "#/components/responses/Unauthorized",
            "description": "Credentials invalid or not provided."
          },
          "404": {
            "$ref": "#/components/responses/Not Found",
            "description": "The requested resource was not found."
          },
          "500": {
            "$ref": "#/components/responses/Internal Server Error",
            "description": "The server encountered an unexpected condition that prevented it from fulfilling the request."
          }
        },
        "security": [
          {
            "bearer": []
          }
        ]
      },
      "delete": {
        "summary": "Delete a track",
        "deprecated": false,
        "description": "Delete a track by ID. Requires authentication.",
        "tags": [
          "tracks"
        ],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "description": "The ID of the resource.",
            "required": true,
            "schema": {
              "type": "integer",
              "description": "The ID of the resource",
              "minimum": 1
            }
          }
        ],
        "responses": {
          "204": {
            "description": "The server successfully processed the request and is not returning any content.",
            "headers": {}
          },
          "401": {
            "$ref": "#/components/responses/Unauthorized",
            "description": "Credentials invalid or not provided."
          },
          "404": {
            "$ref": "#/components/responses/Not Found",
            "description": "The requested resource was not found."
          },
          "500": {
            "$ref": "#/components/responses/Internal Server Error",
            "description": "The server encountered an unexpected condition that prevented it from fulfilling the request."
          }
        },
        "security": [
          {
            "bearer": []
          }
        ]
      }
    },
    "/artists": {
      "get": {
        "summary": "Filter artists",
        "deprecated": false,
        "description": "Get a list of artists using optional filters.",
        "tags": [
          "artists"
        ],
        "parameters": [
          {
            "name": "limit",
            "in": "query",
            "description": "Specifies the maximum number of items to return.",
            "required": false,
            "schema": {
              "type": "integer",
              "description": "Specifies the maximum number of items to return.",
              "default": 20,
              "maximum": 100,
              "minimum": 1
            }
          },
          {
            "name": "offset",
            "in": "query",
            "description": "Specifies the starting index of the data.",
            "required": false,
            "schema": {
              "type": "integer",
              "description": "Specifies the starting index of the data.",
              "minimum": 0,
              "default": 0
            }
          },
          {
            "name": "sort",
            "in": "query",
            "description": "Specifies the column to sort by.",
            "required": false,
            "schema": {
              "type": "string",
              "description": "Specifies the column to sort by.",
              "enum": [
                "created_at",
                "updated_at",
                "id"
              ],
              "default": "id"
            }
          },
          {
            "name": "name",
            "in": "query",
            "description": "The name of the artist.",
            "required": false,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Successful operation.",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "status": {
                      "type": "integer",
                      "description": "HTTP status code",
                      "minimum": 100,
                      "maximum": 999,
                      "default": 200
                    },
                    "href": {
                      "type": "string",
                      "title": "",
                      "description": "self-link"
                    },
                    "next": {
                      "type": [
                        "string",
                        "null"
                      ],
                      "description": "URL to next page"
                    },
                    "previous": {
                      "type": [
                        "string",
                        "null"
                      ],
                      "description": "URL to previous page"
                    },
                    "data": {
                      "type": "array",
                      "items": {
                        "$ref": "#/components/schemas/Artist"
                      }
                    }
                  },
                  "required": [
                    "data",
                    "status",
                    "href",
                    "next",
                    "previous"
                  ]
                },
                "example": {
                  "status": 200,
                  "href": "https://patriciaj.se/tracks-api/api/v1/artists?limit=4&offset=0&sort=id",
                  "next": "https://patriciaj.se/tracks-api/api/v1/artists?limit=4&offset=4&sort=id",
                  "previous": null,
                  "data": [
                    {
                      "id": 1,
                      "href": "https://patriciaj.se/tracks-api/api/v1/artists/1",
                      "created_at": "2026-06-19T12:24:48.345168Z",
                      "updated_at": "2026-06-19T12:24:48.345168Z",
                      "name": "The Killers",
                      "tracks": "https://patriciaj.se/tracks-api/api/v1/tracks?artist_id=1",
                      "albums": [
                        {
                          "id": 1,
                          "href": "https://patriciaj.se/tracks-api/api/v1/albums/1"
                        }
                      ]
                    },
                    {
                      "id": 2,
                      "href": "https://patriciaj.se/tracks-api/api/v1/artists/2",
                      "created_at": "2026-06-19T12:24:48.345168Z",
                      "updated_at": "2026-06-19T12:24:48.345168Z",
                      "name": "Oasis",
                      "tracks": "https://patriciaj.se/tracks-api/api/v1/tracks?artist_id=2",
                      "albums": [
                        {
                          "id": 2,
                          "href": "https://patriciaj.se/tracks-api/api/v1/albums/2"
                        }
                      ]
                    },
                    {
                      "id": 3,
                      "href": "https://patriciaj.se/tracks-api/api/v1/artists/3",
                      "created_at": "2026-06-19T12:24:48.345168Z",
                      "updated_at": "2026-06-19T12:24:48.345168Z",
                      "name": "Nirvana",
                      "tracks": "https://patriciaj.se/tracks-api/api/v1/tracks?artist_id=3",
                      "albums": [
                        {
                          "id": 2,
                          "href": "https://patriciaj.se/tracks-api/api/v1/albums/2"
                        }
                      ]
                    },
                    {
                      "id": 4,
                      "href": "https://patriciaj.se/tracks-api/api/v1/artists/4",
                      "created_at": "2026-06-19T12:24:48.345168Z",
                      "updated_at": "2026-06-19T12:24:48.345168Z",
                      "name": "Franz Ferdinand",
                      "tracks": "https://patriciaj.se/tracks-api/api/v1/tracks?artist_id=4",
                      "albums": [
                        {
                          "id": 4,
                          "href": "https://patriciaj.se/tracks-api/api/v1/albums/4"
                        }
                      ]
                    }
                  ]
                }
              }
            },
            "headers": {}
          },
          "400": {
            "$ref": "#/components/responses/Bad Request",
            "description": "The request cannot or will not be processed due to something that is perceived to be a client error (for example validation error)."
          },
          "500": {
            "$ref": "#/components/responses/Internal Server Error",
            "description": "The server encountered an unexpected condition that prevented it from fulfilling the request."
          }
        },
        "security": []
      }
    },
    "/artists/{id}": {
      "get": {
        "summary": "Get an artist by ID",
        "deprecated": false,
        "description": "Get an artist by ID.",
        "tags": [
          "artists"
        ],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "description": "The artist ID.",
            "required": true,
            "schema": {
              "type": "integer",
              "description": "The ID of the resource.",
              "minimum": 1
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Successful operation.",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "status": {
                      "type": "integer",
                      "description": "HTTP status code",
                      "minimum": 0,
                      "maximum": 999,
                      "default": 200
                    },
                    "data": {
                      "$ref": "#/components/schemas/Artist"
                    }
                  },
                  "required": [
                    "status",
                    "data"
                  ]
                },
                "example": {
                  "status": 200,
                  "data": {
                    "id": 1,
                    "href": "https://patriciaj.se/tracks-api/api/v1/artists/1",
                    "created_at": "2026-06-19T12:24:48.345168Z",
                    "updated_at": "2026-06-19T12:24:48.345168Z",
                    "name": "The Killers",
                    "tracks": "https://patriciaj.se/tracks-api/api/v1/tracks?artist_id=1",
                    "albums": [
                      {
                        "id": 1,
                        "href": "https://patriciaj.se/tracks-api/api/v1/albums/1"
                      }
                    ]
                  }
                }
              }
            },
            "headers": {}
          },
          "404": {
            "$ref": "#/components/responses/Not Found",
            "description": "The requested resource was not found."
          },
          "500": {
            "$ref": "#/components/responses/Internal Server Error",
            "description": "The server encountered an unexpected condition that prevented it from fulfilling the request."
          }
        },
        "security": []
      }
    },
    "/albums": {
      "get": {
        "summary": "Filter albums",
        "deprecated": false,
        "description": "Get a list of albums using optional filters.",
        "tags": [
          "albums"
        ],
        "parameters": [
          {
            "name": "limit",
            "in": "query",
            "description": "Specifies the maximum number of items to return.",
            "required": false,
            "schema": {
              "type": "integer",
              "description": "Specifies the maximum number of items to return.",
              "default": 20,
              "maximum": 100,
              "minimum": 1
            }
          },
          {
            "name": "offset",
            "in": "query",
            "description": "Specifies the starting index of the data.",
            "required": false,
            "schema": {
              "type": "integer",
              "description": "Specifies the starting index of the data.",
              "minimum": 0,
              "default": 0
            }
          },
          {
            "name": "sort",
            "in": "query",
            "description": "Specifies the starting index of the data.",
            "required": false,
            "schema": {
              "type": "string",
              "description": "Specifies the column to sort by.",
              "enum": [
                "created_at",
                "updated_at",
                "id"
              ],
              "default": "id"
            }
          },
          {
            "name": "name",
            "in": "query",
            "description": "The album name.",
            "required": false,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Successful operation.",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "status": {
                      "type": "integer",
                      "description": "HTTP status code",
                      "minimum": 100,
                      "maximum": 999,
                      "default": 200
                    },
                    "href": {
                      "type": "string",
                      "title": "",
                      "description": "self-link"
                    },
                    "next": {
                      "type": [
                        "string",
                        "null"
                      ],
                      "description": "URL to next page"
                    },
                    "previous": {
                      "type": [
                        "string",
                        "null"
                      ],
                      "description": "URL to previous page"
                    },
                    "data": {
                      "type": "array",
                      "items": {
                        "$ref": "#/components/schemas/Album"
                      }
                    }
                  },
                  "required": [
                    "data",
                    "status",
                    "href",
                    "next",
                    "previous"
                  ]
                },
                "example": {
                  "status": 200,
                  "href": "https://patriciaj.se/tracks-api/api/v1/albums?limit=4&offset=0&sort=id",
                  "next": "https://patriciaj.se/tracks-api/api/v1/albums?limit=4&offset=4&sort=id",
                  "previous": null,
                  "data": [
                    {
                      "id": 1,
                      "href": "https://patriciaj.se/tracks-api/api/v1/albums/1",
                      "created_at": "2026-06-19T12:24:50.355529Z",
                      "updated_at": "2026-06-19T12:24:50.355529Z",
                      "name": "Recovered Vol.1 - Slammin' Club Cover Versions",
                      "tracks": "https://patriciaj.se/tracks-api/api/v1/tracks?album_id=1",
                      "artists": [
                        {
                          "id": 1,
                          "href": "https://patriciaj.se/tracks-api/api/v1/artists/1"
                        }
                      ]
                    },
                    {
                      "id": 2,
                      "href": "https://patriciaj.se/tracks-api/api/v1/albums/2",
                      "created_at": "2026-06-19T12:24:50.355529Z",
                      "updated_at": "2026-06-19T12:24:50.355529Z",
                      "name": "Punk Goes 90s",
                      "tracks": "https://patriciaj.se/tracks-api/api/v1/tracks?album_id=2",
                      "artists": [
                        {
                          "id": 2,
                          "href": "https://patriciaj.se/tracks-api/api/v1/artists/2"
                        },
                        {
                          "id": 3,
                          "href": "https://patriciaj.se/tracks-api/api/v1/artists/3"
                        },
                        {
                          "id": 46,
                          "href": "https://patriciaj.se/tracks-api/api/v1/artists/46"
                        },
                        {
                          "id": 493,
                          "href": "https://patriciaj.se/tracks-api/api/v1/artists/493"
                        }
                      ]
                    },
                    {
                      "id": 3,
                      "href": "https://patriciaj.se/tracks-api/api/v1/albums/3",
                      "created_at": "2026-06-19T12:24:50.355529Z",
                      "updated_at": "2026-06-19T12:24:50.355529Z",
                      "name": "Afrodisiac",
                      "tracks": "https://patriciaj.se/tracks-api/api/v1/tracks?album_id=3",
                      "artists": [
                        {
                          "id": 3,
                          "href": "https://patriciaj.se/tracks-api/api/v1/artists/3"
                        },
                        {
                          "id": 629,
                          "href": "https://patriciaj.se/tracks-api/api/v1/artists/629"
                        }
                      ]
                    },
                    {
                      "id": 4,
                      "href": "https://patriciaj.se/tracks-api/api/v1/albums/4",
                      "created_at": "2026-06-19T12:24:50.355529Z",
                      "updated_at": "2026-06-19T12:24:50.355529Z",
                      "name": "Annie_ Let's Not Wait",
                      "tracks": "https://patriciaj.se/tracks-api/api/v1/tracks?album_id=4",
                      "artists": [
                        {
                          "id": 4,
                          "href": "https://patriciaj.se/tracks-api/api/v1/artists/4"
                        }
                      ]
                    }
                  ]
                }
              }
            },
            "headers": {}
          },
          "400": {
            "$ref": "#/components/responses/Bad Request",
            "description": "The request cannot or will not be processed due to something that is perceived to be a client error (for example validation error)."
          },
          "500": {
            "$ref": "#/components/responses/Internal Server Error",
            "description": "The server encountered an unexpected condition that prevented it from fulfilling the request."
          }
        },
        "security": []
      }
    },
    "/albums/{id}": {
      "get": {
        "summary": "Get an album by ID",
        "deprecated": false,
        "description": "Get an album by ID.",
        "tags": [
          "albums"
        ],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "description": "The album ID.",
            "required": true,
            "schema": {
              "type": "integer",
              "description": "The ID of the resource.",
              "minimum": 1
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Successful operation.",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "status": {
                      "type": "integer",
                      "description": "HTTP status code",
                      "minimum": 0,
                      "maximum": 999,
                      "default": 200
                    },
                    "data": {
                      "$ref": "#/components/schemas/Album"
                    }
                  },
                  "required": [
                    "status",
                    "data"
                  ]
                },
                "example": {
                  "status": 200,
                  "data": {
                    "id": 1,
                    "href": "https://patriciaj.se/tracks-api/api/v1/albums/1",
                    "created_at": "2026-06-19T12:24:50.355529Z",
                    "updated_at": "2026-06-19T12:24:50.355529Z",
                    "name": "Recovered Vol.1 - Slammin' Club Cover Versions",
                    "tracks": "https://patriciaj.se/tracks-api/api/v1/tracks?album_id=1",
                    "artists": [
                      {
                        "id": 1,
                        "href": "https://patriciaj.se/tracks-api/api/v1/artists/1"
                      }
                    ]
                  }
                }
              }
            },
            "headers": {}
          },
          "404": {
            "$ref": "#/components/responses/Not Found",
            "description": "The requested resource was not found."
          },
          "500": {
            "$ref": "#/components/responses/Internal Server Error",
            "description": "The server encountered an unexpected condition that prevented it from fulfilling the request."
          }
        },
        "security": []
      }
    }
  },
  "webhooks": {},
  "components": {
    "schemas": {
      "BaseResource": {
        "type": "object",
        "properties": {
          "id": {
            "type": "integer",
            "description": "The ID of the resource.",
            "minimum": 1
          },
          "href": {
            "type": "string",
            "description": "self-link",
            "title": ""
          },
          "created_at": {
            "type": "string",
            "description": "The date and time when the resource was created"
          },
          "updated_at": {
            "type": "string",
            "description": "The date and time when the resource was last modified"
          }
        },
        "required": [
          "id",
          "href",
          "created_at",
          "updated_at"
        ]
      },
      "RelatedResource": {
        "type": "object",
        "properties": {
          "id": {
            "type": "integer",
            "description": "The ID of the resource.",
            "minimum": 1
          },
          "href": {
            "type": "string",
            "description": "Link to the resource.",
            "title": ""
          }
        },
        "required": [
          "id",
          "href"
        ]
      },
      "BasePagination": {
        "type": "object",
        "properties": {
          "status": {
            "type": "integer",
            "description": "HTTP status code",
            "minimum": 100,
            "maximum": 999,
            "default": 200
          },
          "href": {
            "type": "string",
            "title": "",
            "description": "self-link"
          },
          "next": {
            "type": [
              "string",
              "null"
            ],
            "description": "URL to next page"
          },
          "previous": {
            "type": [
              "string",
              "null"
            ],
            "description": "URL to previous page"
          }
        },
        "required": [
          "href",
          "next",
          "previous",
          "status"
        ]
      },
      "Track": {
        "type": "object",
        "properties": {
          "id": {
            "type": "integer",
            "description": "The ID of the resource.",
            "minimum": 1
          },
          "href": {
            "type": "string",
            "description": "self-link",
            "title": ""
          },
          "created_at": {
            "type": "string",
            "description": "The date and time when the resource was created"
          },
          "updated_at": {
            "type": "string",
            "description": "The date and time when the resource was last modified"
          },
          "name": {
            "type": "string",
            "description": "The name of the track."
          },
          "total_playcount": {
            "type": "integer",
            "description": "Number of times the song has been played."
          },
          "spotify_id": {
            "type": [
              "string",
              "null"
            ],
            "description": "The spotify ID."
          },
          "tags": {
            "type": [
              "string",
              "null"
            ],
            "description": "Tags describing the genres the track belongs to."
          },
          "genre": {
            "type": [
              "string",
              "null"
            ],
            "description": "The genre."
          },
          "year": {
            "type": "integer",
            "description": "The year the track was released."
          },
          "duration_ms": {
            "type": [
              "integer",
              "null"
            ],
            "description": "The duration in milliseconds."
          },
          "danceability": {
            "type": [
              "number",
              "null"
            ],
            "description": "An algorithmic estimation of the track danceability."
          },
          "mode": {
            "type": [
              "integer",
              "null"
            ],
            "description": "Major or minor.",
            "enum": [
              0,
              1
            ]
          },
          "valence": {
            "type": [
              "number",
              "null"
            ],
            "description": "An algorithmic estimation of the track valence. Valence describes musical positivity."
          },
          "artists": {
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/RelatedResource"
            }
          },
          "albums": {
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/RelatedResource"
            }
          }
        },
        "required": [
          "name",
          "total_playcount",
          "spotify_id",
          "tags",
          "year",
          "duration_ms",
          "danceability",
          "mode",
          "valence",
          "artists",
          "albums",
          "genre",
          "id",
          "href",
          "created_at",
          "updated_at"
        ]
      },
      "TrackPayload": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string",
            "description": "The name of the track."
          },
          "year": {
            "type": "integer",
            "description": "The year the track was released."
          },
          "artist_ids": {
            "type": "array",
            "items": {
              "type": "integer",
              "minimum": 1
            },
            "minItems": 1,
            "description": "An array containing the IDs of artists that worked on the track. The artist must exist in the artist collection."
          },
          "album_ids": {
            "type": "array",
            "items": {
              "type": "integer",
              "minimum": 1
            },
            "minItems": 1,
            "description": "An array of IDs of albums where the track appears. The album must exist in the albums collection."
          },
          "total_playcount": {
            "type": "integer",
            "description": "Number of times the song has been played."
          },
          "spotify_id": {
            "type": [
              "string",
              "null"
            ],
            "description": "The spotify ID."
          },
          "tags": {
            "type": "array",
            "items": {
              "type": "string"
            },
            "description": "Tags describing the genres the track belongs to."
          },
          "genre": {
            "type": [
              "string",
              "null"
            ],
            "description": "The genre."
          },
          "duration_ms": {
            "type": [
              "integer",
              "null"
            ],
            "description": "The duration in milliseconds."
          },
          "danceability": {
            "type": [
              "number",
              "null"
            ],
            "description": "An algorithmic estimation of the track danceability."
          },
          "mode": {
            "type": [
              "integer",
              "null"
            ],
            "description": "Major or minor.",
            "enum": [
              0,
              1
            ]
          },
          "valence": {
            "type": [
              "number",
              "null"
            ],
            "description": "An algorithmic estimation of the track valence. Valence describes musical positivity."
          }
        },
        "required": [
          "name",
          "year",
          "artist_ids",
          "album_ids"
        ]
      },
      "Artist": {
        "type": "object",
        "properties": {
          "id": {
            "type": "integer",
            "description": "The ID of the resource.",
            "minimum": 1
          },
          "href": {
            "type": "string",
            "description": "self-link",
            "title": ""
          },
          "created_at": {
            "type": "string",
            "description": "The date and time when the resource was created"
          },
          "updated_at": {
            "type": "string",
            "description": "The date and time when the resource was last modified"
          },
          "name": {
            "type": "string",
            "description": "The name of the artist."
          },
          "tracks": {
            "type": "string",
            "description": "URL to the tracks collection filtered by the artist ID."
          },
          "albums": {
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/RelatedResource"
            },
            "description": "The albums the artist has worked on."
          }
        },
        "required": [
          "name",
          "tracks",
          "albums",
          "id",
          "href",
          "created_at",
          "updated_at"
        ]
      },
      "Album": {
        "type": "object",
        "properties": {
          "id": {
            "type": "integer",
            "description": "The ID of the resource.",
            "minimum": 1
          },
          "href": {
            "type": "string",
            "description": "self-link",
            "title": ""
          },
          "created_at": {
            "type": "string",
            "description": "The date and time when the resource was created"
          },
          "updated_at": {
            "type": "string",
            "description": "The date and time when the resource was last modified"
          },
          "name": {
            "type": "string",
            "description": "The album name."
          },
          "tracks": {
            "type": "string",
            "description": "URL to the tracks collection filtered by the album ID."
          },
          "artists": {
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/RelatedResource"
            },
            "description": "Artists that worked on the album."
          }
        },
        "required": [
          "tracks",
          "artists",
          "name",
          "id",
          "href",
          "created_at",
          "updated_at"
        ]
      }
    },
    "responses": {
      "Internal Server Error": {
        "description": "The server encountered an unexpected condition that prevented it from fulfilling the request.",
        "content": {
          "application/json": {
            "schema": {
              "title": "",
              "type": "object",
              "properties": {
                "status": {
                  "type": "integer",
                  "description": "HTTP status code",
                  "default": 500,
                  "minimum": 0,
                  "maximum": 999
                },
                "message": {
                  "type": "string",
                  "description": "Description"
                }
              },
              "required": [
                "status",
                "message"
              ]
            },
            "examples": {
              "Default": {
                "summary": "Default",
                "value": {
                  "status": 500,
                  "message": "The server encountered an unexpected condition that prevented it from fulfilling the request."
                }
              }
            }
          }
        }
      },
      "Bad Request": {
        "description": "The request cannot or will not be processed due to something that is perceived to be a client error (for example validation error).",
        "content": {
          "application/json": {
            "schema": {
              "title": "",
              "type": "object",
              "properties": {
                "status": {
                  "type": "integer",
                  "description": "HTTP status code",
                  "minimum": 0,
                  "maximum": 999,
                  "default": 400
                },
                "message": {
                  "type": "string",
                  "description": "Error description"
                }
              },
              "required": [
                "status",
                "message"
              ]
            },
            "examples": {
              "Example": {
                "summary": "Example",
                "value": {
                  "status": 400,
                  "message": "The request cannot or will not be processed due to something that is perceived to be a client error (for example validation error)."
                }
              }
            }
          }
        }
      },
      "Unauthorized": {
        "description": "Credentials invalid or not provided.",
        "content": {
          "application/json": {
            "schema": {
              "title": "",
              "type": "object",
              "properties": {
                "status": {
                  "type": "integer",
                  "description": "HTTP status code",
                  "default": 401,
                  "minimum": 0,
                  "maximum": 999
                },
                "message": {
                  "type": "string",
                  "title": "",
                  "description": "Description"
                }
              },
              "required": [
                "status",
                "message"
              ]
            },
            "examples": {
              "Default": {
                "summary": "Default",
                "value": {
                  "status": 401,
                  "message": "Credentials invalid or not provided."
                }
              }
            }
          }
        }
      },
      "Not Found": {
        "description": "The requested resource was not found.",
        "content": {
          "application/json": {
            "schema": {
              "title": "",
              "type": "object",
              "properties": {
                "status": {
                  "type": "integer",
                  "description": "HTTP status code",
                  "default": 404,
                  "minimum": 1,
                  "maximum": 999
                },
                "message": {
                  "type": "string",
                  "title": "",
                  "description": "Description"
                }
              },
              "required": [
                "status",
                "message"
              ]
            },
            "examples": {
              "Default": {
                "summary": "Default",
                "value": {
                  "status": 404,
                  "message": "The requested resource was not found."
                }
              }
            }
          }
        }
      }
    },
    "securitySchemes": {
      "bearer": {
        "type": "http",
        "scheme": "bearer"
      }
    }
  },
  "servers": [
    {
      "url": "https://patriciaj.se/tracks-api/api/v1",
      "description": "Prod Env"
    }
  ],
  "security": []
}